FROM binwiederhier/ntfy:latest
USER root
RUN mkdir -p /var/cache/ntfy && chmod 777 /var/cache/ntfy
EXPOSE 8080
ENTRYPOINT ["ntfy"]
CMD ["serve", "--listen-http", ":8080", "--cache-file", "/var/cache/ntfy/cache.db", "--cache-duration", "72h"]
